# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles /app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chtl

# Build rule for target.
chtl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chtl
.PHONY : chtl

# fast build rule for target.
chtl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl.dir/build.make CMakeFiles/chtl.dir/build
.PHONY : chtl/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

CHTL/CHTLGenerator/CHTLGenerator.o: CHTL/CHTLGenerator/CHTLGenerator.cpp.o
.PHONY : CHTL/CHTLGenerator/CHTLGenerator.o

# target to build an object file
CHTL/CHTLGenerator/CHTLGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl.dir/build.make CMakeFiles/chtl.dir/CHTL/CHTLGenerator/CHTLGenerator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/CHTL/CHTLGenerator/CHTLGenerator.cpp.o
.PHONY : CHTL/CHTLGenerator/CHTLGenerator.cpp.o

CHTL/CHTLGenerator/CHTLGenerator.i: CHTL/CHTLGenerator/CHTLGenerator.cpp.i
.PHONY : CHTL/CHTLGenerator/CHTLGenerator.i

# target to preprocess a source file
CHTL/CHTLGenerator/CHTLGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl.dir/build.make CMakeFiles/chtl.dir/CHTL/CHTLGenerator/CHTLGenerator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/CHTL/CHTLGenerator/CHTLGenerator.cpp.i
.PHONY : CHTL/CHTLGenerator/CHTLGenerator.cpp.i

CHTL/CHTLGenerator/CHTLGenerator.s: CHTL/CHTLGenerator/CHTLGenerator.cpp.s
.PHONY : CHTL/CHTLGenerator/CHTLGenerator.s

# target to generate assembly for a file
CHTL/CHTLGenerator/CHTLGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl.dir/build.make CMakeFiles/chtl.dir/CHTL/CHTLGenerator/CHTLGenerator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/CHTL/CHTLGenerator/CHTLGenerator.cpp.s
.PHONY : CHTL/CHTLGenerator/CHTLGenerator.cpp.s

CHTL/CHTLLexer/CHTLLexer.o: CHTL/CHTLLexer/CHTLLexer.cpp.o
.PHONY : CHTL/CHTLLexer/CHTLLexer.o

# target to build an object file
CHTL/CHTLLexer/CHTLLexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl.dir/build.make CMakeFiles/chtl.dir/CHTL/CHTLLexer/CHTLLexer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/CHTL/CHTLLexer/CHTLLexer.cpp.o
.PHONY : CHTL/CHTLLexer/CHTLLexer.cpp.o

CHTL/CHTLLexer/CHTLLexer.i: CHTL/CHTLLexer/CHTLLexer.cpp.i
.PHONY : CHTL/CHTLLexer/CHTLLexer.i

# target to preprocess a source file
CHTL/CHTLLexer/CHTLLexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl.dir/build.make CMakeFiles/chtl.dir/CHTL/CHTLLexer/CHTLLexer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/CHTL/CHTLLexer/CHTLLexer.cpp.i
.PHONY : CHTL/CHTLLexer/CHTLLexer.cpp.i

CHTL/CHTLLexer/CHTLLexer.s: CHTL/CHTLLexer/CHTLLexer.cpp.s
.PHONY : CHTL/CHTLLexer/CHTLLexer.s

# target to generate assembly for a file
CHTL/CHTLLexer/CHTLLexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl.dir/build.make CMakeFiles/chtl.dir/CHTL/CHTLLexer/CHTLLexer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/CHTL/CHTLLexer/CHTLLexer.cpp.s
.PHONY : CHTL/CHTLLexer/CHTLLexer.cpp.s

CHTL/CHTLParser/CHTLParser.o: CHTL/CHTLParser/CHTLParser.cpp.o
.PHONY : CHTL/CHTLParser/CHTLParser.o

# target to build an object file
CHTL/CHTLParser/CHTLParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl.dir/build.make CMakeFiles/chtl.dir/CHTL/CHTLParser/CHTLParser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/CHTL/CHTLParser/CHTLParser.cpp.o
.PHONY : CHTL/CHTLParser/CHTLParser.cpp.o

CHTL/CHTLParser/CHTLParser.i: CHTL/CHTLParser/CHTLParser.cpp.i
.PHONY : CHTL/CHTLParser/CHTLParser.i

# target to preprocess a source file
CHTL/CHTLParser/CHTLParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl.dir/build.make CMakeFiles/chtl.dir/CHTL/CHTLParser/CHTLParser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/CHTL/CHTLParser/CHTLParser.cpp.i
.PHONY : CHTL/CHTLParser/CHTLParser.cpp.i

CHTL/CHTLParser/CHTLParser.s: CHTL/CHTLParser/CHTLParser.cpp.s
.PHONY : CHTL/CHTLParser/CHTLParser.s

# target to generate assembly for a file
CHTL/CHTLParser/CHTLParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl.dir/build.make CMakeFiles/chtl.dir/CHTL/CHTLParser/CHTLParser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/CHTL/CHTLParser/CHTLParser.cpp.s
.PHONY : CHTL/CHTLParser/CHTLParser.cpp.s

Test/GeneratorTest.o: Test/GeneratorTest.cpp.o
.PHONY : Test/GeneratorTest.o

# target to build an object file
Test/GeneratorTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/Test/GeneratorTest.cpp.o
.PHONY : Test/GeneratorTest.cpp.o

Test/GeneratorTest.i: Test/GeneratorTest.cpp.i
.PHONY : Test/GeneratorTest.i

# target to preprocess a source file
Test/GeneratorTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/Test/GeneratorTest.cpp.i
.PHONY : Test/GeneratorTest.cpp.i

Test/GeneratorTest.s: Test/GeneratorTest.cpp.s
.PHONY : Test/GeneratorTest.s

# target to generate assembly for a file
Test/GeneratorTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/Test/GeneratorTest.cpp.s
.PHONY : Test/GeneratorTest.cpp.s

Test/LexerTest.o: Test/LexerTest.cpp.o
.PHONY : Test/LexerTest.o

# target to build an object file
Test/LexerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/Test/LexerTest.cpp.o
.PHONY : Test/LexerTest.cpp.o

Test/LexerTest.i: Test/LexerTest.cpp.i
.PHONY : Test/LexerTest.i

# target to preprocess a source file
Test/LexerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/Test/LexerTest.cpp.i
.PHONY : Test/LexerTest.cpp.i

Test/LexerTest.s: Test/LexerTest.cpp.s
.PHONY : Test/LexerTest.s

# target to generate assembly for a file
Test/LexerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/Test/LexerTest.cpp.s
.PHONY : Test/LexerTest.cpp.s

Test/ParserTest.o: Test/ParserTest.cpp.o
.PHONY : Test/ParserTest.o

# target to build an object file
Test/ParserTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/Test/ParserTest.cpp.o
.PHONY : Test/ParserTest.cpp.o

Test/ParserTest.i: Test/ParserTest.cpp.i
.PHONY : Test/ParserTest.i

# target to preprocess a source file
Test/ParserTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/Test/ParserTest.cpp.i
.PHONY : Test/ParserTest.cpp.i

Test/ParserTest.s: Test/ParserTest.cpp.s
.PHONY : Test/ParserTest.s

# target to generate assembly for a file
Test/ParserTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/Test/ParserTest.cpp.s
.PHONY : Test/ParserTest.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl.dir/build.make CMakeFiles/chtl.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl.dir/build.make CMakeFiles/chtl.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl.dir/build.make CMakeFiles/chtl.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... chtl"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... run_tests"
	@echo "... CHTL/CHTLGenerator/CHTLGenerator.o"
	@echo "... CHTL/CHTLGenerator/CHTLGenerator.i"
	@echo "... CHTL/CHTLGenerator/CHTLGenerator.s"
	@echo "... CHTL/CHTLLexer/CHTLLexer.o"
	@echo "... CHTL/CHTLLexer/CHTLLexer.i"
	@echo "... CHTL/CHTLLexer/CHTLLexer.s"
	@echo "... CHTL/CHTLParser/CHTLParser.o"
	@echo "... CHTL/CHTLParser/CHTLParser.i"
	@echo "... CHTL/CHTLParser/CHTLParser.s"
	@echo "... Test/GeneratorTest.o"
	@echo "... Test/GeneratorTest.i"
	@echo "... Test/GeneratorTest.s"
	@echo "... Test/LexerTest.o"
	@echo "... Test/LexerTest.i"
	@echo "... Test/LexerTest.s"
	@echo "... Test/ParserTest.o"
	@echo "... Test/ParserTest.i"
	@echo "... Test/ParserTest.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
