# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles /app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chtl_lib

# Build rule for target.
chtl_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chtl_lib
.PHONY : chtl_lib

# fast build rule for target.
chtl_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/build
.PHONY : chtl_lib/fast

#=============================================================================
# Target rules for targets named chtl_compiler

# Build rule for target.
chtl_compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chtl_compiler
.PHONY : chtl_compiler

# fast build rule for target.
chtl_compiler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_compiler.dir/build.make CMakeFiles/chtl_compiler.dir/build
.PHONY : chtl_compiler/fast

#=============================================================================
# Target rules for targets named test_parser

# Build rule for target.
test_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_parser
.PHONY : test_parser

# fast build rule for target.
test_parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parser.dir/build.make CMakeFiles/test_parser.dir/build
.PHONY : test_parser/fast

#=============================================================================
# Target rules for targets named test_scanner

# Build rule for target.
test_scanner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_scanner
.PHONY : test_scanner

# fast build rule for target.
test_scanner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scanner.dir/build.make CMakeFiles/test_scanner.dir/build
.PHONY : test_scanner/fast

#=============================================================================
# Target rules for targets named test_unified_scanner

# Build rule for target.
test_unified_scanner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_unified_scanner
.PHONY : test_unified_scanner

# fast build rule for target.
test_unified_scanner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_unified_scanner.dir/build.make CMakeFiles/test_unified_scanner.dir/build
.PHONY : test_unified_scanner/fast

#=============================================================================
# Target rules for targets named test_runner

# Build rule for target.
test_runner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_runner
.PHONY : test_runner

# fast build rule for target.
test_runner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_runner.dir/build.make CMakeFiles/test_runner.dir/build
.PHONY : test_runner/fast

miniz.o: miniz.c.o
.PHONY : miniz.o

# target to build an object file
miniz.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/miniz.c.o
.PHONY : miniz.c.o

miniz.i: miniz.c.i
.PHONY : miniz.i

# target to preprocess a source file
miniz.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/miniz.c.i
.PHONY : miniz.c.i

miniz.s: miniz.c.s
.PHONY : miniz.s

# target to generate assembly for a file
miniz.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/miniz.c.s
.PHONY : miniz.c.s

src/CHTL/CHTLGenerator/CHTLGenerator.o: src/CHTL/CHTLGenerator/CHTLGenerator.cpp.o
.PHONY : src/CHTL/CHTLGenerator/CHTLGenerator.o

# target to build an object file
src/CHTL/CHTLGenerator/CHTLGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTL/CHTLGenerator/CHTLGenerator.cpp.o
.PHONY : src/CHTL/CHTLGenerator/CHTLGenerator.cpp.o

src/CHTL/CHTLGenerator/CHTLGenerator.i: src/CHTL/CHTLGenerator/CHTLGenerator.cpp.i
.PHONY : src/CHTL/CHTLGenerator/CHTLGenerator.i

# target to preprocess a source file
src/CHTL/CHTLGenerator/CHTLGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTL/CHTLGenerator/CHTLGenerator.cpp.i
.PHONY : src/CHTL/CHTLGenerator/CHTLGenerator.cpp.i

src/CHTL/CHTLGenerator/CHTLGenerator.s: src/CHTL/CHTLGenerator/CHTLGenerator.cpp.s
.PHONY : src/CHTL/CHTLGenerator/CHTLGenerator.s

# target to generate assembly for a file
src/CHTL/CHTLGenerator/CHTLGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTL/CHTLGenerator/CHTLGenerator.cpp.s
.PHONY : src/CHTL/CHTLGenerator/CHTLGenerator.cpp.s

src/CHTL/CHTLLexer/CHTLLexer.o: src/CHTL/CHTLLexer/CHTLLexer.cpp.o
.PHONY : src/CHTL/CHTLLexer/CHTLLexer.o

# target to build an object file
src/CHTL/CHTLLexer/CHTLLexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTL/CHTLLexer/CHTLLexer.cpp.o
.PHONY : src/CHTL/CHTLLexer/CHTLLexer.cpp.o

src/CHTL/CHTLLexer/CHTLLexer.i: src/CHTL/CHTLLexer/CHTLLexer.cpp.i
.PHONY : src/CHTL/CHTLLexer/CHTLLexer.i

# target to preprocess a source file
src/CHTL/CHTLLexer/CHTLLexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTL/CHTLLexer/CHTLLexer.cpp.i
.PHONY : src/CHTL/CHTLLexer/CHTLLexer.cpp.i

src/CHTL/CHTLLexer/CHTLLexer.s: src/CHTL/CHTLLexer/CHTLLexer.cpp.s
.PHONY : src/CHTL/CHTLLexer/CHTLLexer.s

# target to generate assembly for a file
src/CHTL/CHTLLexer/CHTLLexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTL/CHTLLexer/CHTLLexer.cpp.s
.PHONY : src/CHTL/CHTLLexer/CHTLLexer.cpp.s

src/CHTL/CHTLLoader/CHTLLoader.o: src/CHTL/CHTLLoader/CHTLLoader.cpp.o
.PHONY : src/CHTL/CHTLLoader/CHTLLoader.o

# target to build an object file
src/CHTL/CHTLLoader/CHTLLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTL/CHTLLoader/CHTLLoader.cpp.o
.PHONY : src/CHTL/CHTLLoader/CHTLLoader.cpp.o

src/CHTL/CHTLLoader/CHTLLoader.i: src/CHTL/CHTLLoader/CHTLLoader.cpp.i
.PHONY : src/CHTL/CHTLLoader/CHTLLoader.i

# target to preprocess a source file
src/CHTL/CHTLLoader/CHTLLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTL/CHTLLoader/CHTLLoader.cpp.i
.PHONY : src/CHTL/CHTLLoader/CHTLLoader.cpp.i

src/CHTL/CHTLLoader/CHTLLoader.s: src/CHTL/CHTLLoader/CHTLLoader.cpp.s
.PHONY : src/CHTL/CHTLLoader/CHTLLoader.s

# target to generate assembly for a file
src/CHTL/CHTLLoader/CHTLLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTL/CHTLLoader/CHTLLoader.cpp.s
.PHONY : src/CHTL/CHTLLoader/CHTLLoader.cpp.s

src/CHTL/CHTLParser/CHTLParser.o: src/CHTL/CHTLParser/CHTLParser.cpp.o
.PHONY : src/CHTL/CHTLParser/CHTLParser.o

# target to build an object file
src/CHTL/CHTLParser/CHTLParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTL/CHTLParser/CHTLParser.cpp.o
.PHONY : src/CHTL/CHTLParser/CHTLParser.cpp.o

src/CHTL/CHTLParser/CHTLParser.i: src/CHTL/CHTLParser/CHTLParser.cpp.i
.PHONY : src/CHTL/CHTLParser/CHTLParser.i

# target to preprocess a source file
src/CHTL/CHTLParser/CHTLParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTL/CHTLParser/CHTLParser.cpp.i
.PHONY : src/CHTL/CHTLParser/CHTLParser.cpp.i

src/CHTL/CHTLParser/CHTLParser.s: src/CHTL/CHTLParser/CHTLParser.cpp.s
.PHONY : src/CHTL/CHTLParser/CHTLParser.s

# target to generate assembly for a file
src/CHTL/CHTLParser/CHTLParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTL/CHTLParser/CHTLParser.cpp.s
.PHONY : src/CHTL/CHTLParser/CHTLParser.cpp.s

src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.o: src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.cpp.o
.PHONY : src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.o

# target to build an object file
src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.cpp.o
.PHONY : src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.cpp.o

src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.i: src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.cpp.i
.PHONY : src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.i

# target to preprocess a source file
src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.cpp.i
.PHONY : src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.cpp.i

src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.s: src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.cpp.s
.PHONY : src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.s

# target to generate assembly for a file
src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.cpp.s
.PHONY : src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.cpp.s

src/CHTLJS/CHTLJSLexer/CHTLJSLexer.o: src/CHTLJS/CHTLJSLexer/CHTLJSLexer.cpp.o
.PHONY : src/CHTLJS/CHTLJSLexer/CHTLJSLexer.o

# target to build an object file
src/CHTLJS/CHTLJSLexer/CHTLJSLexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTLJS/CHTLJSLexer/CHTLJSLexer.cpp.o
.PHONY : src/CHTLJS/CHTLJSLexer/CHTLJSLexer.cpp.o

src/CHTLJS/CHTLJSLexer/CHTLJSLexer.i: src/CHTLJS/CHTLJSLexer/CHTLJSLexer.cpp.i
.PHONY : src/CHTLJS/CHTLJSLexer/CHTLJSLexer.i

# target to preprocess a source file
src/CHTLJS/CHTLJSLexer/CHTLJSLexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTLJS/CHTLJSLexer/CHTLJSLexer.cpp.i
.PHONY : src/CHTLJS/CHTLJSLexer/CHTLJSLexer.cpp.i

src/CHTLJS/CHTLJSLexer/CHTLJSLexer.s: src/CHTLJS/CHTLJSLexer/CHTLJSLexer.cpp.s
.PHONY : src/CHTLJS/CHTLJSLexer/CHTLJSLexer.s

# target to generate assembly for a file
src/CHTLJS/CHTLJSLexer/CHTLJSLexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTLJS/CHTLJSLexer/CHTLJSLexer.cpp.s
.PHONY : src/CHTLJS/CHTLJSLexer/CHTLJSLexer.cpp.s

src/CHTLJS/CHTLJSParser/CHTLJSParser.o: src/CHTLJS/CHTLJSParser/CHTLJSParser.cpp.o
.PHONY : src/CHTLJS/CHTLJSParser/CHTLJSParser.o

# target to build an object file
src/CHTLJS/CHTLJSParser/CHTLJSParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTLJS/CHTLJSParser/CHTLJSParser.cpp.o
.PHONY : src/CHTLJS/CHTLJSParser/CHTLJSParser.cpp.o

src/CHTLJS/CHTLJSParser/CHTLJSParser.i: src/CHTLJS/CHTLJSParser/CHTLJSParser.cpp.i
.PHONY : src/CHTLJS/CHTLJSParser/CHTLJSParser.i

# target to preprocess a source file
src/CHTLJS/CHTLJSParser/CHTLJSParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTLJS/CHTLJSParser/CHTLJSParser.cpp.i
.PHONY : src/CHTLJS/CHTLJSParser/CHTLJSParser.cpp.i

src/CHTLJS/CHTLJSParser/CHTLJSParser.s: src/CHTLJS/CHTLJSParser/CHTLJSParser.cpp.s
.PHONY : src/CHTLJS/CHTLJSParser/CHTLJSParser.s

# target to generate assembly for a file
src/CHTLJS/CHTLJSParser/CHTLJSParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CHTLJS/CHTLJSParser/CHTLJSParser.cpp.s
.PHONY : src/CHTLJS/CHTLJSParser/CHTLJSParser.cpp.s

src/CJMOD/API/Syntax.o: src/CJMOD/API/Syntax.cpp.o
.PHONY : src/CJMOD/API/Syntax.o

# target to build an object file
src/CJMOD/API/Syntax.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CJMOD/API/Syntax.cpp.o
.PHONY : src/CJMOD/API/Syntax.cpp.o

src/CJMOD/API/Syntax.i: src/CJMOD/API/Syntax.cpp.i
.PHONY : src/CJMOD/API/Syntax.i

# target to preprocess a source file
src/CJMOD/API/Syntax.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CJMOD/API/Syntax.cpp.i
.PHONY : src/CJMOD/API/Syntax.cpp.i

src/CJMOD/API/Syntax.s: src/CJMOD/API/Syntax.cpp.s
.PHONY : src/CJMOD/API/Syntax.s

# target to generate assembly for a file
src/CJMOD/API/Syntax.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CJMOD/API/Syntax.cpp.s
.PHONY : src/CJMOD/API/Syntax.cpp.s

src/CJMOD/Scanner/CJMODScanner.o: src/CJMOD/Scanner/CJMODScanner.cpp.o
.PHONY : src/CJMOD/Scanner/CJMODScanner.o

# target to build an object file
src/CJMOD/Scanner/CJMODScanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CJMOD/Scanner/CJMODScanner.cpp.o
.PHONY : src/CJMOD/Scanner/CJMODScanner.cpp.o

src/CJMOD/Scanner/CJMODScanner.i: src/CJMOD/Scanner/CJMODScanner.cpp.i
.PHONY : src/CJMOD/Scanner/CJMODScanner.i

# target to preprocess a source file
src/CJMOD/Scanner/CJMODScanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CJMOD/Scanner/CJMODScanner.cpp.i
.PHONY : src/CJMOD/Scanner/CJMODScanner.cpp.i

src/CJMOD/Scanner/CJMODScanner.s: src/CJMOD/Scanner/CJMODScanner.cpp.s
.PHONY : src/CJMOD/Scanner/CJMODScanner.s

# target to generate assembly for a file
src/CJMOD/Scanner/CJMODScanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CJMOD/Scanner/CJMODScanner.cpp.s
.PHONY : src/CJMOD/Scanner/CJMODScanner.cpp.s

src/CodeMerger/CodeMerger.o: src/CodeMerger/CodeMerger.cpp.o
.PHONY : src/CodeMerger/CodeMerger.o

# target to build an object file
src/CodeMerger/CodeMerger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CodeMerger/CodeMerger.cpp.o
.PHONY : src/CodeMerger/CodeMerger.cpp.o

src/CodeMerger/CodeMerger.i: src/CodeMerger/CodeMerger.cpp.i
.PHONY : src/CodeMerger/CodeMerger.i

# target to preprocess a source file
src/CodeMerger/CodeMerger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CodeMerger/CodeMerger.cpp.i
.PHONY : src/CodeMerger/CodeMerger.cpp.i

src/CodeMerger/CodeMerger.s: src/CodeMerger/CodeMerger.cpp.s
.PHONY : src/CodeMerger/CodeMerger.s

# target to generate assembly for a file
src/CodeMerger/CodeMerger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CodeMerger/CodeMerger.cpp.s
.PHONY : src/CodeMerger/CodeMerger.cpp.s

src/CompilerDispatcher/CompilerDispatcher.o: src/CompilerDispatcher/CompilerDispatcher.cpp.o
.PHONY : src/CompilerDispatcher/CompilerDispatcher.o

# target to build an object file
src/CompilerDispatcher/CompilerDispatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CompilerDispatcher/CompilerDispatcher.cpp.o
.PHONY : src/CompilerDispatcher/CompilerDispatcher.cpp.o

src/CompilerDispatcher/CompilerDispatcher.i: src/CompilerDispatcher/CompilerDispatcher.cpp.i
.PHONY : src/CompilerDispatcher/CompilerDispatcher.i

# target to preprocess a source file
src/CompilerDispatcher/CompilerDispatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CompilerDispatcher/CompilerDispatcher.cpp.i
.PHONY : src/CompilerDispatcher/CompilerDispatcher.cpp.i

src/CompilerDispatcher/CompilerDispatcher.s: src/CompilerDispatcher/CompilerDispatcher.cpp.s
.PHONY : src/CompilerDispatcher/CompilerDispatcher.s

# target to generate assembly for a file
src/CompilerDispatcher/CompilerDispatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/CompilerDispatcher/CompilerDispatcher.cpp.s
.PHONY : src/CompilerDispatcher/CompilerDispatcher.cpp.s

src/Scanner/CHTLUnifiedScanner.o: src/Scanner/CHTLUnifiedScanner.cpp.o
.PHONY : src/Scanner/CHTLUnifiedScanner.o

# target to build an object file
src/Scanner/CHTLUnifiedScanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/Scanner/CHTLUnifiedScanner.cpp.o
.PHONY : src/Scanner/CHTLUnifiedScanner.cpp.o

src/Scanner/CHTLUnifiedScanner.i: src/Scanner/CHTLUnifiedScanner.cpp.i
.PHONY : src/Scanner/CHTLUnifiedScanner.i

# target to preprocess a source file
src/Scanner/CHTLUnifiedScanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/Scanner/CHTLUnifiedScanner.cpp.i
.PHONY : src/Scanner/CHTLUnifiedScanner.cpp.i

src/Scanner/CHTLUnifiedScanner.s: src/Scanner/CHTLUnifiedScanner.cpp.s
.PHONY : src/Scanner/CHTLUnifiedScanner.s

# target to generate assembly for a file
src/Scanner/CHTLUnifiedScanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_lib.dir/build.make CMakeFiles/chtl_lib.dir/src/Scanner/CHTLUnifiedScanner.cpp.s
.PHONY : src/Scanner/CHTLUnifiedScanner.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_compiler.dir/build.make CMakeFiles/chtl_compiler.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_compiler.dir/build.make CMakeFiles/chtl_compiler.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chtl_compiler.dir/build.make CMakeFiles/chtl_compiler.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/test_parser.o: tests/test_parser.cpp.o
.PHONY : tests/test_parser.o

# target to build an object file
tests/test_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parser.dir/build.make CMakeFiles/test_parser.dir/tests/test_parser.cpp.o
.PHONY : tests/test_parser.cpp.o

tests/test_parser.i: tests/test_parser.cpp.i
.PHONY : tests/test_parser.i

# target to preprocess a source file
tests/test_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parser.dir/build.make CMakeFiles/test_parser.dir/tests/test_parser.cpp.i
.PHONY : tests/test_parser.cpp.i

tests/test_parser.s: tests/test_parser.cpp.s
.PHONY : tests/test_parser.s

# target to generate assembly for a file
tests/test_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parser.dir/build.make CMakeFiles/test_parser.dir/tests/test_parser.cpp.s
.PHONY : tests/test_parser.cpp.s

tests/test_runner.o: tests/test_runner.cpp.o
.PHONY : tests/test_runner.o

# target to build an object file
tests/test_runner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_runner.dir/build.make CMakeFiles/test_runner.dir/tests/test_runner.cpp.o
.PHONY : tests/test_runner.cpp.o

tests/test_runner.i: tests/test_runner.cpp.i
.PHONY : tests/test_runner.i

# target to preprocess a source file
tests/test_runner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_runner.dir/build.make CMakeFiles/test_runner.dir/tests/test_runner.cpp.i
.PHONY : tests/test_runner.cpp.i

tests/test_runner.s: tests/test_runner.cpp.s
.PHONY : tests/test_runner.s

# target to generate assembly for a file
tests/test_runner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_runner.dir/build.make CMakeFiles/test_runner.dir/tests/test_runner.cpp.s
.PHONY : tests/test_runner.cpp.s

tests/test_scanner.o: tests/test_scanner.cpp.o
.PHONY : tests/test_scanner.o

# target to build an object file
tests/test_scanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scanner.dir/build.make CMakeFiles/test_scanner.dir/tests/test_scanner.cpp.o
.PHONY : tests/test_scanner.cpp.o

tests/test_scanner.i: tests/test_scanner.cpp.i
.PHONY : tests/test_scanner.i

# target to preprocess a source file
tests/test_scanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scanner.dir/build.make CMakeFiles/test_scanner.dir/tests/test_scanner.cpp.i
.PHONY : tests/test_scanner.cpp.i

tests/test_scanner.s: tests/test_scanner.cpp.s
.PHONY : tests/test_scanner.s

# target to generate assembly for a file
tests/test_scanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scanner.dir/build.make CMakeFiles/test_scanner.dir/tests/test_scanner.cpp.s
.PHONY : tests/test_scanner.cpp.s

tests/test_unified_scanner.o: tests/test_unified_scanner.cpp.o
.PHONY : tests/test_unified_scanner.o

# target to build an object file
tests/test_unified_scanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_unified_scanner.dir/build.make CMakeFiles/test_unified_scanner.dir/tests/test_unified_scanner.cpp.o
.PHONY : tests/test_unified_scanner.cpp.o

tests/test_unified_scanner.i: tests/test_unified_scanner.cpp.i
.PHONY : tests/test_unified_scanner.i

# target to preprocess a source file
tests/test_unified_scanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_unified_scanner.dir/build.make CMakeFiles/test_unified_scanner.dir/tests/test_unified_scanner.cpp.i
.PHONY : tests/test_unified_scanner.cpp.i

tests/test_unified_scanner.s: tests/test_unified_scanner.cpp.s
.PHONY : tests/test_unified_scanner.s

# target to generate assembly for a file
tests/test_unified_scanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_unified_scanner.dir/build.make CMakeFiles/test_unified_scanner.dir/tests/test_unified_scanner.cpp.s
.PHONY : tests/test_unified_scanner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chtl_compiler"
	@echo "... chtl_lib"
	@echo "... test_parser"
	@echo "... test_runner"
	@echo "... test_scanner"
	@echo "... test_unified_scanner"
	@echo "... miniz.o"
	@echo "... miniz.i"
	@echo "... miniz.s"
	@echo "... src/CHTL/CHTLGenerator/CHTLGenerator.o"
	@echo "... src/CHTL/CHTLGenerator/CHTLGenerator.i"
	@echo "... src/CHTL/CHTLGenerator/CHTLGenerator.s"
	@echo "... src/CHTL/CHTLLexer/CHTLLexer.o"
	@echo "... src/CHTL/CHTLLexer/CHTLLexer.i"
	@echo "... src/CHTL/CHTLLexer/CHTLLexer.s"
	@echo "... src/CHTL/CHTLLoader/CHTLLoader.o"
	@echo "... src/CHTL/CHTLLoader/CHTLLoader.i"
	@echo "... src/CHTL/CHTLLoader/CHTLLoader.s"
	@echo "... src/CHTL/CHTLParser/CHTLParser.o"
	@echo "... src/CHTL/CHTLParser/CHTLParser.i"
	@echo "... src/CHTL/CHTLParser/CHTLParser.s"
	@echo "... src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.o"
	@echo "... src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.i"
	@echo "... src/CHTLJS/CHTLJSGenerator/CHTLJSGenerator.s"
	@echo "... src/CHTLJS/CHTLJSLexer/CHTLJSLexer.o"
	@echo "... src/CHTLJS/CHTLJSLexer/CHTLJSLexer.i"
	@echo "... src/CHTLJS/CHTLJSLexer/CHTLJSLexer.s"
	@echo "... src/CHTLJS/CHTLJSParser/CHTLJSParser.o"
	@echo "... src/CHTLJS/CHTLJSParser/CHTLJSParser.i"
	@echo "... src/CHTLJS/CHTLJSParser/CHTLJSParser.s"
	@echo "... src/CJMOD/API/Syntax.o"
	@echo "... src/CJMOD/API/Syntax.i"
	@echo "... src/CJMOD/API/Syntax.s"
	@echo "... src/CJMOD/Scanner/CJMODScanner.o"
	@echo "... src/CJMOD/Scanner/CJMODScanner.i"
	@echo "... src/CJMOD/Scanner/CJMODScanner.s"
	@echo "... src/CodeMerger/CodeMerger.o"
	@echo "... src/CodeMerger/CodeMerger.i"
	@echo "... src/CodeMerger/CodeMerger.s"
	@echo "... src/CompilerDispatcher/CompilerDispatcher.o"
	@echo "... src/CompilerDispatcher/CompilerDispatcher.i"
	@echo "... src/CompilerDispatcher/CompilerDispatcher.s"
	@echo "... src/Scanner/CHTLUnifiedScanner.o"
	@echo "... src/Scanner/CHTLUnifiedScanner.i"
	@echo "... src/Scanner/CHTLUnifiedScanner.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/test_parser.o"
	@echo "... tests/test_parser.i"
	@echo "... tests/test_parser.s"
	@echo "... tests/test_runner.o"
	@echo "... tests/test_runner.i"
	@echo "... tests/test_runner.s"
	@echo "... tests/test_scanner.o"
	@echo "... tests/test_scanner.i"
	@echo "... tests/test_scanner.s"
	@echo "... tests/test_unified_scanner.o"
	@echo "... tests/test_unified_scanner.i"
	@echo "... tests/test_unified_scanner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
