add_test([=[LexerTest.BasicElementsAndAttributes]=]  /app/run_tests [==[--gtest_filter=LexerTest.BasicElementsAndAttributes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.BasicElementsAndAttributes]=]  PROPERTIES WORKING_DIRECTORY /app SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.CommentsAndWhitespace]=]  /app/run_tests [==[--gtest_filter=LexerTest.CommentsAndWhitespace]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.CommentsAndWhitespace]=]  PROPERTIES WORKING_DIRECTORY /app SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.TemplateDefinitionAndUsage]=]  /app/run_tests [==[--gtest_filter=ParserTest.TemplateDefinitionAndUsage]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.TemplateDefinitionAndUsage]=]  PROPERTIES WORKING_DIRECTORY /app SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GeneratorTest.StyleTemplate]=]  /app/run_tests [==[--gtest_filter=GeneratorTest.StyleTemplate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GeneratorTest.StyleTemplate]=]  PROPERTIES WORKING_DIRECTORY /app SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GeneratorTest.ElementTemplate]=]  /app/run_tests [==[--gtest_filter=GeneratorTest.ElementTemplate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GeneratorTest.ElementTemplate]=]  PROPERTIES WORKING_DIRECTORY /app SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GeneratorTest.TemplateInheritance]=]  /app/run_tests [==[--gtest_filter=GeneratorTest.TemplateInheritance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GeneratorTest.TemplateInheritance]=]  PROPERTIES WORKING_DIRECTORY /app SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  run_tests_TESTS LexerTest.BasicElementsAndAttributes LexerTest.CommentsAndWhitespace ParserTest.TemplateDefinitionAndUsage GeneratorTest.StyleTemplate GeneratorTest.ElementTemplate GeneratorTest.TemplateInheritance)
