add_test([=[LexerTest.BasicElementsAndAttributes]=]  /app/run_tests [==[--gtest_filter=LexerTest.BasicElementsAndAttributes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.BasicElementsAndAttributes]=]  PROPERTIES WORKING_DIRECTORY /app SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.CommentsAndWhitespace]=]  /app/run_tests [==[--gtest_filter=LexerTest.CommentsAndWhitespace]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.CommentsAndWhitespace]=]  PROPERTIES WORKING_DIRECTORY /app SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.CustomStyleDefinitionAndUsage]=]  /app/run_tests [==[--gtest_filter=ParserTest.CustomStyleDefinitionAndUsage]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.CustomStyleDefinitionAndUsage]=]  PROPERTIES WORKING_DIRECTORY /app SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GeneratorTest.CustomStyleSpecialization]=]  /app/run_tests [==[--gtest_filter=GeneratorTest.CustomStyleSpecialization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GeneratorTest.CustomStyleSpecialization]=]  PROPERTIES WORKING_DIRECTORY /app SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  run_tests_TESTS LexerTest.BasicElementsAndAttributes LexerTest.CommentsAndWhitespace ParserTest.CustomStyleDefinitionAndUsage GeneratorTest.CustomStyleSpecialization)
