#include "CodeMerger.h"
#include <string>

namespace CHTL {

    CodeMerger::CodeMerger() {}

    std::string CodeMerger::mergeToFinalHtml(const FinalCompilationResult& result) {
        // This is a placeholder implementation.
        // The real merger will need to handle placeholders generated by the scanner.
        // For now, it just combines the pieces into a standard HTML file structure.

        std::string finalHtml = result.html;

        // Embed CSS if it exists
        if (!result.css.empty()) {
            std::string styleTag = "<style>\n" + result.css + "\n</style>";
            // A simple approach to find where to inject the style.
            // A more robust solution might be needed later.
            size_t head_pos = finalHtml.find("</head>");
            if (head_pos != std::string::npos) {
                finalHtml.insert(head_pos, styleTag);
            } else {
                // fallback if no head tag, just append
                finalHtml += styleTag;
            }
        }

        // Embed JS if it exists
        if (!result.js.empty()) {
            std::string scriptTag = "<script>\n" + result.js + "\n</script>";
            size_t body_pos = finalHtml.find("</body>");
            if (body_pos != std::string::npos) {
                finalHtml.insert(body_pos, scriptTag);
            } else {
                // fallback if no body tag
                finalHtml += scriptTag;
            }
        }

        return finalHtml;
    }

} // namespace CHTL
