package CHTL.Lexer;

public enum TokenType {
    // Literals
    IDENTIFIER, STRING, NUMBER,

    // Symbols
    LBRACE, RBRACE, LBRACKET, RBRACKET,
    COLON, EQUALS, SEMICOLON, COMMA,
    AT, DOT,

    // Keywords
    TEXT, STYLE, SCRIPT,
    TEMPLATE, CUSTOM, IMPORT, NAMESPACE, EXCEPT,
    FROM, AS, WITH, INHERIT, DELETE, INSERT,
    AFTER, BEFORE, REPLACE,

    EOF
}
