[package]
name = "chtl_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
notify = "8.2.0"
pest = "2.8.1"
pest_derive = "2.8.1"

[dev-dependencies]
tempfile = "3.1.0"
